export const page = "#fff7ed"
export const background = "#fffdf8"
export const surface = "#fff2df"
export const text = "#34231f"
export const muted = "#8a6258"
export const accent = "#ef6547"
export const border = "#efd1bd"
export const textOnAccent = "#fffdf8"

export const shadow = "rgba(82, 45, 31, 0.12)"
